import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowRight, ChefHat, Check, CircleAlert, Clock3, Leaf, Plus, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import "./styles.css";
import "./pagination.css";

const fallbackAllergens = ["Peanut", "Tree nuts", "Dairy", "Gluten", "Soy", "Egg", "Shellfish"];
const fallbackRecipes = [
  { id: "lemon-herb-chicken", name: "Lemon Herb Chicken", description: "Bright, juicy chicken with roasted vegetables.", timeMinutes: 35, difficulty: "Easy", allergens: [] },
  { id: "coconut-curry", name: "Coconut Vegetable Curry", description: "Creamy coconut curry packed with colorful vegetables.", timeMinutes: 30, difficulty: "Easy", allergens: ["Soy", "Gluten"] },
  { id: "chocolate-chip-cookies", name: "Chocolate Chip Cookies", description: "A classic bake with a crisp edge and soft center.", timeMinutes: 25, difficulty: "Medium", allergens: ["Gluten", "Dairy", "Peanut"] },
];
const API_URL = (import.meta.env.VITE_API_URL || "").replace(/\/$/, "");
const apiFetch = (path) => fetch(`${API_URL}${path}`);
const normalizeRecipeResponse = (data) => Array.isArray(data) ? { recipes: data, total: data.length, totalPages: 1 } : { recipes: Array.isArray(data?.recipes) ? data.recipes : [], total: Number(data?.total) || 0, totalPages: Number(data?.totalPages) || 1 };

function App() {
  const [selected, setSelected] = useState([]); const [recipes, setRecipes] = useState(fallbackRecipes); const [total, setTotal] = useState(fallbackRecipes.length); const [totalPages, setTotalPages] = useState(1); const [page, setPage] = useState(1); const [connected, setConnected] = useState(false); const [query, setQuery] = useState(""); const [allergenOptions, setAllergenOptions] = useState(fallbackAllergens); const [showEditor, setShowEditor] = useState(false); const [editorMessage, setEditorMessage] = useState(""); const [toast, setToast] = useState(null); const [form, setForm] = useState({ name: "", description: "", timeMinutes: 30, difficulty: "Easy", ingredients: "" });
  const showToast = (type, message) => { setToast({ type, message }); window.setTimeout(() => setToast(null), 4500); };
  useEffect(() => { Promise.all([apiFetch("/api/health"), apiFetch("/api/allergens")]).then(async ([health, allergens]) => { if (health.ok) setConnected(true); if (allergens.ok) { const data = await allergens.json(); if (data.length) setAllergenOptions(data.map((item) => item.name)); } }).catch(() => showToast("info", "Backend unavailable. Showing demo data.")); }, []);
  useEffect(() => { apiFetch(`/api/recipes?allergens=${encodeURIComponent(selected.join(","))}&search=${encodeURIComponent(query)}&page=${page}&pageSize=6`).then((response) => { if (!response.ok) throw new Error("Could not load recipes from the backend."); return response.json(); }).then((data) => { const normalized = normalizeRecipeResponse(data); setRecipes(normalized.recipes); setTotal(normalized.total); setTotalPages(normalized.totalPages); }).catch((error) => showToast("error", error.message)); }, [selected, query, page]);
  const toggle = (allergen) => { setPage(1); setSelected((items) => items.includes(allergen) ? items.filter((item) => item !== allergen) : [...items, allergen]); };
  const visible = recipes;
  const submitRecipe = async (event) => { event.preventDefault(); setEditorMessage(""); const ingredients = form.ingredients.split("\n").map((line) => { const [name, allergens = "", categories = "", substitutes = ""] = line.split("|"); return { name: name.trim(), allergens: allergens.split(",").map((item) => item.trim()).filter(Boolean), categories: categories.split(",").map((item) => item.trim()).filter(Boolean), substitutes: substitutes.split(",").map((name) => ({ name: name.trim() })).filter((item) => item.name) }; }).filter((item) => item.name); try { const response = await fetch(`${API_URL}/api/recipes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, timeMinutes: Number(form.timeMinutes), ingredients }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Could not save recipe"); showToast("success", "Recipe saved to Neo4j."); setForm({ name: "", description: "", timeMinutes: 30, difficulty: "Easy", ingredients: "" }); setShowEditor(false); setPage(1); const refreshed = await apiFetch(`/api/recipes?allergens=${encodeURIComponent(selected.join(","))}&search=${encodeURIComponent(query)}&page=1&pageSize=6`); if (refreshed.ok) { const data = normalizeRecipeResponse(await refreshed.json()); setRecipes(data.recipes); setTotal(data.total); setTotalPages(data.totalPages); } const allergensResponse = await apiFetch("/api/allergens"); if (allergensResponse.ok) setAllergenOptions((await allergensResponse.json()).map((item) => item.name)); } catch (error) { setEditorMessage(error.message); showToast("error", error.message); } };
  return <main>
    {toast && <div className={`toast ${toast.type}`} role="status"><span>{toast.type === "success" ? "✓" : toast.type === "error" ? "!" : "i"}</span>{toast.message}<button onClick={() => setToast(null)} aria-label="Dismiss notification">×</button></div>}
    <nav><div className="brand"><span className="brand-mark"><ChefHat size={20} /></span><span>Graph<span className="lime">DB</span>App</span></div><div className="nav-note"><span className={connected ? "dot live" : "dot"} />{connected ? "Neo4j connected" : "Demo mode"}</div></nav>
    <section className="hero"><div className="eyebrow"><Sparkles size={15} /> SMART FOOD SAFETY</div><h1>Cook with confidence.<br /><em>Know every connection.</em></h1><p>Explore recipes through the ingredient graph. Select your allergens and we’ll trace every path to keep your plate safe.</p><div className="graph-line"><span>Recipe</span><ArrowRight size={15} /><span>Ingredient</span><ArrowRight size={15} /><span>Allergen</span></div></section>
    <section className="workspace"><aside><div className="section-label">YOUR ALLERGEN PROFILE</div><h2>What should we avoid?</h2><p className="muted">Choose one or more allergens to personalize your safe recipe map.</p><div className="allergen-list">{allergenOptions.map((allergen) => <button key={allergen} className={selected.includes(allergen) ? "allergen active" : "allergen"} onClick={() => toggle(allergen)}><span className="check">{selected.includes(allergen) && <Check size={14} />}</span>{allergen}</button>)}</div><div className="profile-card"><ShieldCheck size={19} /><div><strong>{selected.length ? `${selected.length} allergen${selected.length > 1 ? "s" : ""} tracked` : "No allergens selected"}</strong><span>{selected.length ? "Safety checks are active" : "Add allergens to begin"}</span></div></div></aside>
      <div className="results"><div className="results-head"><div><div className="section-label">SAFE RECIPE NAVIGATOR</div><h2>{selected.length ? "Recipes that fit your profile" : "Start with a safe plate"}</h2></div><div className="result-actions"><button className="add-button" onClick={() => setShowEditor(!showEditor)}><Plus size={15} /> Add recipe</button><div className="search"><Search size={16} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search recipes" /></div></div></div>
        {showEditor && <form className="editor" onSubmit={submitRecipe}><div className="section-label">DEMO DATA ENTRY</div><h3>Add a recipe to the graph</h3><div className="editor-grid"><input required placeholder="Recipe name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input placeholder="Description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><input type="number" min="1" value={form.timeMinutes} onChange={(event) => setForm({ ...form, timeMinutes: event.target.value })} /><select value={form.difficulty} onChange={(event) => setForm({ ...form, difficulty: event.target.value })}><option>Easy</option><option>Medium</option><option>Hard</option></select></div><textarea required placeholder={'One ingredient per line: name | allergen1,allergen2 | category1,category2 | substitute1,substitute2'} value={form.ingredients} onChange={(event) => setForm({ ...form, ingredients: event.target.value })} /><button className="save-button" type="submit">Save to Neo4j</button>{editorMessage && <span className="editor-message">{editorMessage}</span>}</form>}
        {selected.length > 0 && <div className="notice"><CircleAlert size={17} /><span>Recipes are filtered by multi-hop allergen traversal: Recipe → Ingredient → Allergen.</span></div>}<div className="recipe-grid">{visible.map((recipe) => <article className="recipe-card" key={recipe.id}><div className="recipe-image"><Leaf size={29} /><span>{recipe.difficulty}</span></div><div className="recipe-body"><div className="recipe-meta"><span><Clock3 size={14} />{recipe.timeMinutes || "—"} min</span><span><Users size={14} />4 servings</span></div><h3>{recipe.name}</h3><p>{recipe.description}</p><div className="tags">{(recipe.allergens || []).length ? recipe.allergens.map((allergen) => <span className="tag warning" key={allergen}>{allergen}</span>) : <span className="tag safe"><ShieldCheck size={13} /> Safe for profile</span>}</div></div></article>)}</div>{visible.length === 0 && <div className="empty">No matching recipes found. Try another search or broaden your profile.</div>}</div>
    </section><div className="pagination"><span>Showing {recipes.length} of {total} recipes</span><button disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Next</button></div><footer><span>Graph-powered food intelligence</span><span>Always verify labels and consult a medical professional.</span></footer>
  </main>;
}
createRoot(document.getElementById("root")).render(<App />);
